### ISSUE TITLE
tailwind 공부해오기 + 써보기

### ISSUE THREAD

**Issue by Skyrich2000** [42-world/rookies-Frontend#9]
tailwind 써보고 여기 쓰레드에 짧게 감상문 남겨오십쇼

**Comment by Skyrich2000** [comment]
next app 에도 적용해보기

**Comment by Seojunhwan** [comment]
tailwind is verygood but 커스터마이징 안되는 줄 알고 조금 싫다,, 생각 했었는데 잘 된다니 다행이네용
+ ring 같은 기능 너무 조음

**Comment by chichoon** [comment]
헉 지금봄

**Comment by raejun92** [comment]
https://tailwindcomponents.com/cheatsheet/
